name: NotSee
version: '${project.version}'
main: com.abbas.notsee.core.NotSee


commands:
  help:
    description: Shows the help menu
    aliases: [h]
  Youtube:
    description: Opens the youtube channel
    aliases: [yt]
  ticktok:
    description: Opens the ticktok channel
    aliases: [tt]
  about:
    description: Shows the plugin information
    aliases: [info]
  discord:
    description: Opens the discord server
    aliases: [dc]
  telegram:
    description: Opens the telegram channel
    aliases: [tg]
  build:
    description: Opens the build server
    aliases: [bs]
permissions:
  notsee.mehelp:
    description: Allows players to use the help command
    default: true
  notsee.mehelp.reload:
    description: Allows players to reload the plugin
    default: op
  notsee.breakblocks:
    description: Allows players to break blocks
    default: false
