name: NotSee
version: '${project.version}'
main: com.abbas.notsee.core.NotSee


commands:
  help:
    description: Shows the help menu
    usage: /help
    aliases: [h]
permissions:
  notsee.mehelp:
    description: Allows players to use the help command
    default: true
  notsee.mehelp.reload:
    description: Allows players to reload the plugin
    default: op
  notsee.breakblocks:
    description: Allows players to break blocks
    default: false
